# Generated by Django 2.2.5 on 2019-11-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('yelp_link', models.CharField(blank=True, max_length=100, null=True)),
                ('timeofday', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('type_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timeofday', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('type_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
