# Generated by Django 2.2.5 on 2019-11-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='locality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sight',
            name='locality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
